go-server:
  image: gocd/gocd-server:v17.10.0
  ports:
    - '8153:8153'
    - '8154:8154'
 
goagent:
  image: gocd/gocd-agent-ubuntu-16.04:v17.10.0
  links:
    - go-server
  environment:
    GO_SERVER_URL: https://go-server:8154/go
